"""Layer playground slide for the BytePlus decks (slides-design skill).

One or two images, each shown as a clean background plus its cut-out objects (transparent PNG layers).
In the browser the audience can drag any object, resize it from a corner, rotate it from the top handle
(Shift snaps to 15 degrees), drop it on the other image, hide the backgrounds, hold to compare with the
original image, and reset. Clicks only hit an object's visible pixels: every layer carries a small
alpha mask (40 columns wide) computed from its PNG.

Pieces:
    LAYER_CSS / LAYER_JS     the styles and the runtime (already inside templates/byteplus*/template.html)
    layer_wrap(manifest)     the slide content (a .ly-wrap block) for one manifest; layer_wrap(None) = the
                             placeholder layout the templates ship with (no sample images)
    python scripts/layer_slide.py masks <manifest.json>
                             (re)compute every layer's "mask" from its PNG (needs Pillow)
    python scripts/layer_slide.py sync <deck.html>
                             put the current LAYER_CSS / LAYER_JS into a deck or template (replace or add)

Manifest (layers.json; image paths are relative to the manifest's own folder):
{
  "canvases": [
    {"title": "SUMMER FIZZ", "note": "13 layers + background", "ratio": 1.7778, "tray": "#3f9f95",
     "background": "fizz/background.jpg", "original": "fizz/original.jpg",
     "layers": [                                   # bottom → top
       {"src": "fizz/l01.png", "name": "Title", "box": [x, y, w, h], "mask": "40,5,0110…"}
     ]}
  ]
}
box = left, top, width, height of the layer in % of the canvas. "tray" = the thumbnail tile colour (pick one
that the cut-outs read well on). Two canvases at most.
"""
import html
import json
import sys
from pathlib import Path

MASK_COLS = 40

LAYER_CSS = """
      /* ── Layer playground (.ly-wrap) — generated by scripts/layer_slide.py ─────────────────────────── */
      .ly-wrap {
        --ly-gap: calc(1.6 * var(--u));
        --ly-cap: calc(1.5 * var(--u));
        --ly-under: calc(5.4 * var(--u));
        flex: 1; min-height: 0;
        display: flex; flex-direction: column; gap: 1.2vh;
        padding-top: var(--gap-sm);
        position: relative;
        font-family: var(--f-body);
      }
      .ly-pair {
        flex: 1; min-height: 0;
        container-type: size;
        display: flex; justify-content: center; gap: var(--ly-gap);
      }
      .ly-poster {
        --r: 1.7778;
        width: min(calc((100cqw - var(--ly-gap) * (var(--ly-n, 2) - 1)) / var(--ly-n, 2)),
                   calc((100cqh - var(--ly-cap) - var(--ly-under) - 2 * 0.8vh) * var(--r)));
        margin: 0; min-width: 0;
        display: flex; flex-direction: column; gap: 0.8vh;
      }
      .ly-poster figcaption {
        height: var(--ly-cap);
        display: flex; align-items: baseline; gap: calc(0.8 * var(--u));
        font-family: var(--f-mono); font-size: var(--sz-label); letter-spacing: 0.14em; text-transform: uppercase;
        color: var(--c-fg-2);
      }
      .ly-poster figcaption b { color: var(--c-accent); font-weight: 600; }
      .ly-stage { position: relative; aspect-ratio: var(--r); }   /* holds the clipped canvas + the unclipped selection box */
      .ly-stage.src { z-index: 5; }
      .ly-canvas {
        position: absolute; inset: 0;
        overflow: hidden; touch-action: none; user-select: none; -webkit-user-select: none;
        box-shadow: 0 calc(0.8 * var(--u)) calc(2.2 * var(--u)) rgba(0, 0, 0, 0.28);
        background-color: #1c2433;
        background-image: linear-gradient(45deg, #2a3346 25%, transparent 25%, transparent 75%, #2a3346 75%),
                          linear-gradient(45deg, #2a3346 25%, transparent 25%, transparent 75%, #2a3346 75%);
        background-size: calc(1.2 * var(--u)) calc(1.2 * var(--u));
        background-position: 0 0, calc(0.6 * var(--u)) calc(0.6 * var(--u));
      }
      .ly-wrap.dragging .ly-canvas { overflow: visible; }
      .ly-canvas.target { outline: 3px solid var(--c-accent); outline-offset: 3px; }
      .ly-canvas.over { cursor: grab; }
      .ly-wrap.dragging, .ly-wrap.dragging * { cursor: grabbing !important; }
      .ly-base, .ly-orig {
        position: absolute; inset: 0; width: 100%; height: 100%; display: block;
        transition: opacity 0.25s;
      }
      .ly-orig { z-index: 400; opacity: 0; pointer-events: none; }
      .ly-wrap.cmp .ly-orig, .ly-canvas.cmp1 .ly-orig { opacity: 1; }
      .ly-wrap.nobg .ly-base { opacity: 0; }
      .ly-layer {
        position: absolute; display: block; max-width: none; margin: 0;
        pointer-events: none; transform-origin: 50% 50%; transition: filter 0.15s;
      }
      .ly-layer.anim { transition: left 0.45s, top 0.45s, width 0.45s, height 0.45s, transform 0.45s; }
      .ly-layer.hov { filter: drop-shadow(0 0 1.5px var(--c-accent)) drop-shadow(0 0 1.5px var(--c-accent)); }
      .ly-layer.sel { filter: drop-shadow(0 10px 16px rgba(0, 0, 0, 0.4)); }
      .ly-box {
        position: absolute; z-index: 300; pointer-events: none; transform-origin: 50% 50%;
        border: 1.5px dashed var(--c-accent);
      }
      .ly-box[hidden] { display: none; }
      .ly-box i {
        position: absolute; width: 13px; height: 13px; border-radius: 4px; pointer-events: auto;
        background: #fff; border: 2px solid var(--c-accent); cursor: nwse-resize;
      }
      .ly-box i[data-h="nw"] { left: -7px; top: -7px; }
      .ly-box i[data-h="se"] { right: -7px; bottom: -7px; }
      .ly-box i[data-h="ne"] { right: -7px; top: -7px; cursor: nesw-resize; }
      .ly-box i[data-h="sw"] { left: -7px; bottom: -7px; cursor: nesw-resize; }
      .ly-box i.rot {
        left: 50%; top: -34px; margin-left: -8px; width: 16px; height: 16px; border-radius: 50%;
        background: var(--c-accent); border-color: #fff; cursor: grab; box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }
      .ly-box i.rot::after { content: ""; position: absolute; left: 5px; top: 14px; width: 2px; height: 19px; background: var(--c-accent); }
      .ly-size {
        position: absolute; left: 50%; bottom: -30px; transform: translateX(-50%); white-space: nowrap;
        background: var(--c-accent); color: #fff; font-family: var(--f-body); font-size: 11.5px; font-weight: 700;
        padding: 2px 8px; border-radius: 6px;
      }
      .ly-under {
        --ly-tile: calc((var(--ly-under) - 0.4 * var(--u)) / 2);
        height: var(--ly-under);
        display: grid; grid-template-columns: calc(var(--ly-under) * 16 / 9) minmax(0, 1fr); grid-template-rows: var(--ly-under);
        gap: calc(0.5 * var(--u));
      }
      .ly-origcard {
        position: relative; height: var(--ly-under); border: 0; padding: 0; overflow: hidden; cursor: pointer; background: #0b1733;
      }
      .ly-origcard img { width: 100%; height: 100%; object-fit: contain; display: block; }
      .ly-origcard span {
        position: absolute; left: 4px; bottom: 4px; padding: 1px 6px; border-radius: 4px;
        background: rgba(11, 23, 51, 0.82); color: #fff; font-family: var(--f-body); font-size: calc(0.62 * var(--u)); font-weight: 700;
      }
      .ly-origcard:hover { outline: 2px solid var(--c-accent); outline-offset: 1px; }
      .ly-tray {
        display: grid; grid-template-columns: repeat(7, minmax(0, 1fr)); grid-auto-rows: var(--ly-tile);
        gap: calc(0.4 * var(--u)); align-content: start;
      }
      .ly-tray button {
        min-width: 0; height: var(--ly-tile); padding: 3px; cursor: pointer;
        display: grid; place-items: center;
        background: var(--tray, #3a3f86); border: 1px solid transparent; border-radius: 6px;
        transition: border-color 0.15s, opacity 0.15s;
      }
      .ly-tray button img { max-width: 100%; max-height: calc(var(--ly-tile) - 8px); object-fit: contain; display: block; }
      .ly-tray button:hover { border-color: var(--c-accent); }
      .ly-tray button.on { border: 2px solid var(--c-accent); }
      .ly-tray button.away { opacity: 0.4; }
      /* placeholder (layer_wrap(None)): striped boxes until real layers exist */
      .ly-canvas.ly-empty, .ly-origcard.ly-empty { background: none; box-shadow: none; cursor: default; }
      .ly-empty > .ph { position: absolute; inset: 0; border: 1px dashed var(--c-border); font-size: var(--sz-label); }
      .ly-tray > .ph { height: var(--ly-tile); border: 1px dashed var(--c-border); border-radius: 6px; }
      .ly-bar { display: flex; align-items: center; flex-wrap: wrap; gap: calc(1.2 * var(--u)); }
      .ly-tools { display: flex; gap: calc(0.5 * var(--u)); }
      .ly-tools button {
        font-family: var(--f-body); font-size: calc(0.85 * var(--u)); font-weight: 600; cursor: pointer;
        padding: calc(0.45 * var(--u)) calc(0.9 * var(--u)); border-radius: 6px;
        color: var(--c-fg); background: transparent; border: 1px solid var(--c-border);
      }
      .ly-tools button:hover { border-color: var(--c-accent); }
      .ly-tools button[aria-pressed="true"], .ly-tools .ly-cmp:active { background: var(--c-accent); border-color: var(--c-accent); color: #fff; }
      .ly-hint { margin: 0; font-size: calc(0.85 * var(--u)); color: var(--c-fg-2); }
      .ly-hint b { color: var(--c-fg); font-weight: 600; }
"""

LAYER_JS = """
    <script>
      /* Layer playground (.ly-wrap): move / resize / rotate cut-out layers and drag them between the
         images of one wrap. Generated by scripts/layer_slide.py; sits beside the presentation engine. */
      (function () {
        "use strict";
        function initLayers(wrap) {
          var box = wrap.querySelector(".ly-box"), lab = box.querySelector(".ly-size");
          var C = [].slice.call(wrap.querySelectorAll(".ly-canvas"));
          var L = [].slice.call(wrap.querySelectorAll(".ly-layer")).map(function (el) {
            var s = el.style, m = el.dataset.mask.split(",");
            var o = { x: parseFloat(s.left), y: parseFloat(s.top), w: parseFloat(s.width), h: parseFloat(s.height), z: s.zIndex };
            return { el: el, c: el.parentElement, home: el.parentElement, m: [+m[0], +m[1], m[2]], name: el.alt,
                     x: o.x, y: o.y, w: o.w, h: o.h, r: 0, o: o };
          });
          var sel = null, hov = null, act = null;
          function R(c) { return c.getBoundingClientRect(); }
          function rad(d) { return d * Math.PI / 180; }
          function place(l) {
            l.el.style.left = l.x + "%"; l.el.style.top = l.y + "%";
            l.el.style.width = l.w + "%"; l.el.style.height = l.h + "%";
            l.el.style.transform = "rotate(" + l.r + "deg)";
          }
          function ctr(l) { var r = R(l.c); return [r.left + (l.x + l.w / 2) / 100 * r.width, r.top + (l.y + l.h / 2) / 100 * r.height]; }
          /* topmost layer whose visible pixels (mask) are under the point */
          function hit(c, px, py) {
            var r = R(c), best = null, bz = -1;
            L.forEach(function (l) {
              if (l.c !== c) return;
              var z = +l.el.style.zIndex;
              if (z <= bz) return;
              var p = ctr(l), a = -rad(l.r), dx = px - p[0], dy = py - p[1];
              var qx = dx * Math.cos(a) - dy * Math.sin(a), qy = dx * Math.sin(a) + dy * Math.cos(a);
              var u = qx / (l.w / 100 * r.width) + 0.5, v = qy / (l.h / 100 * r.height) + 0.5;
              if (u < 0 || v < 0 || u >= 1 || v >= 1) return;
              if (l.m[2][Math.floor(v * l.m[1]) * l.m[0] + Math.floor(u * l.m[0])] === "1") { best = l; bz = z; }
            });
            return best;
          }
          function canvasAt(x, y) {
            return C.filter(function (c) { var r = R(c); return x >= r.left && x <= r.right && y >= r.top && y <= r.bottom; })[0];
          }
          function showBox() {
            if (!sel) { box.hidden = true; return; }
            sel.c.parentElement.appendChild(box);   /* the stage: same box as the canvas, not clipped */
            box.style.left = sel.x + "%"; box.style.top = sel.y + "%";
            box.style.width = sel.w + "%"; box.style.height = sel.h + "%";
            box.style.transform = "rotate(" + sel.r + "deg)";
            var ang = ((Math.round(sel.r) % 360) + 360) % 360;
            lab.textContent = sel.name + " · " + Math.round(sel.w / sel.o.w * 100) + "%" + (ang ? " · " + ang + "°" : "");
            lab.style.transform = "translateX(-50%) rotate(" + (-sel.r) + "deg)";
            box.hidden = false;
          }
          var T = [].slice.call(wrap.querySelectorAll(".ly-tray button"));
          function byKey(k) { return L.filter(function (l) { return l.el.dataset.k === k; })[0]; }
          function sync() {
            T.forEach(function (b) { var l = byKey(b.dataset.k); b.classList.toggle("on", l === sel); b.classList.toggle("away", l.c !== l.home); });
          }
          function select(l) {
            if (sel) sel.el.classList.remove("sel");
            sel = l;
            if (l) l.el.classList.add("sel");
            showBox(); sync();
          }
          function setHov(l) {
            if (hov === l) return;
            if (hov) hov.el.classList.remove("hov");
            hov = l;
            if (l && l !== sel) l.el.classList.add("hov");
            C.forEach(function (c) { c.classList.toggle("over", !!l && l.c === c); });
          }
          function topZ(c) {
            return Math.max.apply(null, [1].concat(L.filter(function (l) { return l.c === c; }).map(function (l) { return +l.el.style.zIndex; }))) + 1;
          }
          wrap.addEventListener("pointerdown", function (e) {
            if (e.button) return;
            var hd = e.target.closest(".ly-box i"), l;
            if (hd && sel) {
              l = sel;
              var p = ctr(l);
              act = hd.dataset.h === "rot"
                ? { mode: "rot", l: l, cx: p[0], cy: p[1], a0: Math.atan2(e.clientY - p[1], e.clientX - p[0]), r0: l.r }
                : { mode: "size", l: l, cx: p[0], cy: p[1], d0: Math.hypot(e.clientX - p[0], e.clientY - p[1]) || 1,
                    w0: l.w, h0: l.h, x0: l.x + l.w / 2, y0: l.y + l.h / 2 };
            } else {
              var c = e.target.closest(".ly-canvas");
              if (!c) return;
              l = hit(c, e.clientX, e.clientY);
              select(l);
              if (!l) return;
              act = { mode: "move", l: l, sx: e.clientX, sy: e.clientY, x: l.x, y: l.y, prev: { x: l.x, y: l.y } };
              l.c.parentElement.classList.add("src");
              wrap.classList.add("dragging");
            }
            l.el.classList.remove("anim");
            wrap.setPointerCapture(e.pointerId);
            e.preventDefault();
          });
          wrap.addEventListener("pointermove", function (e) {
            if (!act) {
              var c = e.target.closest(".ly-canvas");
              setHov(c ? hit(c, e.clientX, e.clientY) : null);
              return;
            }
            var l = act.l, r = R(l.c);
            if (act.mode === "move") {
              l.x = act.x + (e.clientX - act.sx) / r.width * 100;
              l.y = act.y + (e.clientY - act.sy) / r.height * 100;
              var t = canvasAt(e.clientX, e.clientY);
              C.forEach(function (c) { c.classList.toggle("target", c === t && c !== l.c); });
            } else if (act.mode === "size") {
              var k = Math.hypot(e.clientX - act.cx, e.clientY - act.cy) / act.d0, s0 = act.w0 / l.o.w;
              k = Math.max(0.2 / s0, Math.min(4 / s0, k));
              l.w = act.w0 * k; l.h = act.h0 * k; l.x = act.x0 - l.w / 2; l.y = act.y0 - l.h / 2;
            } else {
              var d = (Math.atan2(e.clientY - act.cy, e.clientX - act.cx) - act.a0) * 180 / Math.PI + act.r0;
              l.r = e.shiftKey ? Math.round(d / 15) * 15 : d;
            }
            place(l); showBox();
          });
          function end(e) {
            if (!act) return;
            var a = act; act = null;
            wrap.classList.remove("dragging");
            C.forEach(function (c) { c.classList.remove("target"); c.parentElement.classList.remove("src"); });
            if (a.mode !== "move") return;
            var l = a.l, t = canvasAt(e.clientX, e.clientY);
            if (!t) {  /* dropped outside every image: glide back */
              l.el.classList.add("anim"); l.x = a.prev.x; l.y = a.prev.y; place(l); showBox();
              return;
            }
            if (t !== l.c) {  /* dropped on the other image: keep its screen position, put it on top */
              var r0 = R(l.c), r1 = R(t);
              l.x = ((l.x / 100 * r0.width) + r0.left - r1.left) / r1.width * 100;
              l.y = ((l.y / 100 * r0.height) + r0.top - r1.top) / r1.height * 100;
              l.el.style.zIndex = topZ(t);
              t.appendChild(l.el); l.c = t;
            }
            l.x = Math.max(-l.w * 0.6, Math.min(100 - l.w * 0.4, l.x));
            l.y = Math.max(-l.h * 0.6, Math.min(100 - l.h * 0.4, l.y));
            place(l); showBox(); sync();
          }
          wrap.addEventListener("pointerup", end);
          wrap.addEventListener("pointercancel", end);
          wrap.addEventListener("pointerleave", function () { if (!act) setHov(null); });
          document.addEventListener("pointerdown", function (e) { if (sel && !wrap.contains(e.target)) select(null); });

          var bg = wrap.querySelector(".ly-bg");
          bg.addEventListener("click", function () {
            var on = bg.getAttribute("aria-pressed") !== "true";
            bg.setAttribute("aria-pressed", String(on));
            wrap.classList.toggle("nobg", on);
          });
          function hold(btn, on, off) {
            btn.addEventListener("pointerdown", function (e) { e.stopPropagation(); on(); });
            ["pointerup", "pointerleave", "pointercancel"].forEach(function (t) { btn.addEventListener(t, off); });
          }
          hold(wrap.querySelector(".ly-cmp"), function () { select(null); wrap.classList.add("cmp"); },
               function () { wrap.classList.remove("cmp"); });
          [].forEach.call(wrap.querySelectorAll(".ly-origcard"), function (b) {
            var cv = b.closest(".ly-poster").querySelector(".ly-canvas");
            hold(b, function () { cv.classList.add("cmp1"); }, function () { cv.classList.remove("cmp1"); });
          });
          wrap.querySelector(".ly-reset").addEventListener("click", function () {
            select(null);
            bg.setAttribute("aria-pressed", "false");
            wrap.classList.remove("nobg");
            L.forEach(function (l) {
              if (l.c !== l.home) { l.home.appendChild(l.el); l.c = l.home; }
              l.el.style.zIndex = l.o.z;
              l.x = l.o.x; l.y = l.o.y; l.w = l.o.w; l.h = l.o.h; l.r = 0;
              l.el.classList.add("anim");
              place(l);
            });
            sync();
          });
          T.forEach(function (b) {
            var l = byKey(b.dataset.k);
            b.addEventListener("pointerdown", function (e) { e.stopPropagation(); });
            b.addEventListener("click", function () { select(sel === l ? null : l); });
            b.addEventListener("mouseenter", function () { setHov(l); });
            b.addEventListener("mouseleave", function () { setHov(null); });
          });
        }
        [].forEach.call(document.querySelectorAll(".ly-wrap"), initLayers);
        /* a drag on an image must not turn into a slide swipe on touch screens */
        ["touchstart", "touchend"].forEach(function (t) {
          window.addEventListener(t, function (e) {
            if (e.target.closest && e.target.closest(".ly-canvas")) e.stopPropagation();
          }, true);
        });
      })();
    </script>
"""

TOOLS = '''            <div class="ly-tools">
              <button type="button" class="ly-bg" aria-pressed="false">Hide backgrounds</button>
              <button type="button" class="ly-cmp">Hold to see originals</button>
              <button type="button" class="ly-reset">Reset</button>
            </div>'''

BOX = ('          <div class="ly-box" hidden><i data-h="nw"></i><i data-h="ne"></i><i data-h="sw"></i>'
       '<i data-h="se"></i><i data-h="rot" class="rot"></i><span class="ly-size"></span></div>')


def esc(t):
    return html.escape(str(t), quote=True)


def _canvas(cv, key, img):
    title, layers = cv["title"], cv["layers"]
    imgs = [f'<img class="ly-base" src="{img}{cv["background"]}" alt="" draggable="false" />']
    for i, ly in enumerate(layers, 1):
        x, y, w, h = ly["box"]
        imgs.append(f'<img class="ly-layer" data-k="{key}{i}" data-mask="{ly["mask"]}" src="{img}{ly["src"]}" '
                    f'alt="{esc(ly["name"])}" draggable="false" '
                    f'style="left:{x}%;top:{y}%;width:{w}%;height:{h}%;z-index:{i + 1}" />')
    imgs.append(f'<img class="ly-orig" src="{img}{cv["original"]}" alt="" draggable="false" />')
    tray = "".join(f'<button type="button" data-k="{key}{i}" title="{esc(ly["name"])}">'
                   f'<img src="{img}{ly["src"]}" alt="{esc(ly["name"])}" /></button>'
                   for i, ly in reversed(list(enumerate(layers, 1))))
    canvas_imgs = "\n".join("                " + t for t in imgs)
    return f'''            <figure class="ly-poster" style="--r: {cv.get("ratio", 1.7778)}; --tray: {cv.get("tray", "#3a3f86")}">
              <figcaption><b>{esc(title)}</b><span>{esc(cv.get("note", f"{len(layers)} layers + background"))}</span></figcaption>
              <div class="ly-stage"><div class="ly-canvas">
{canvas_imgs}
              </div></div>
              <div class="ly-under">
                <button type="button" class="ly-origcard" title="Hold to show the original over the editable image"><img src="{img}{cv["original"]}" alt="Original: {esc(title)}" /><span>Original · hold to compare</span></button>
                <div class="ly-tray">{tray}</div>
              </div>
            </figure>'''


def _placeholder(i):
    tiles = "".join('<span class="ph"></span>' for _ in range(6))
    return f'''            <figure class="ly-poster">
              <figcaption><b>[Image {i}]</b><span>[N layers + background]</span></figcaption>
              <div class="ly-stage"><div class="ly-canvas ly-empty"><div class="ph">Background + cut-out layers<br />(layers.json)</div></div></div>
              <div class="ly-under">
                <div class="ly-origcard ly-empty"><div class="ph">Original</div></div>
                <div class="ly-tray">{tiles}</div>
              </div>
            </figure>'''


def layer_wrap(manifest, img="assets/img/layers/", delay=3):
    """The .ly-wrap block for a feature slide's body. manifest = dict or path to layers.json;
    img = the manifest's folder as the deck sees it. manifest=None gives the two-image placeholder
    layout (striped boxes, no images) that the templates ship with."""
    if manifest is None:
        posters = "\n".join(_placeholder(i) for i in (1, 2))
        return f'''          <div class="ly-wrap" data-anim="fade-up" data-delay="{delay}">
            <div class="ly-pair" style="--ly-n: 2">
{posters}
            </div>
            <div class="ly-bar">
{TOOLS}
              <p class="ly-hint"><b>Drag</b> to move · <b>corner</b> to resize · <b>top handle</b> to rotate · <b>drop on the other image</b> to move it across</p>
            </div>
{BOX}
          </div>'''
    if not isinstance(manifest, dict):
        manifest = json.loads(Path(manifest).read_text(encoding="utf-8"))
    cvs = manifest["canvases"]
    assert 1 <= len(cvs) <= 2, "one or two canvases"
    missing = [ly["src"] for cv in cvs for ly in cv["layers"] if not ly.get("mask")]
    assert not missing, f"no mask for {missing[:3]} — run: python scripts/layer_slide.py masks <manifest>"
    hint = ("<b>Drag</b> to move · <b>corner</b> to resize · <b>top handle</b> to rotate"
            + (" · <b>drop on the other image</b> to move it across" if len(cvs) == 2 else ""))
    posters = "\n".join(_canvas(cv, "ab"[i], img) for i, cv in enumerate(cvs))
    return f'''          <div class="ly-wrap" data-anim="fade-up" data-delay="{delay}">
            <div class="ly-pair" style="--ly-n: {len(cvs)}">
{posters}
            </div>
            <div class="ly-bar">
{TOOLS}
              <p class="ly-hint">{hint}</p>
            </div>
{BOX}
          </div>'''


def mask(png, cols=MASK_COLS, alpha_min=24, cover=0.08):
    """'cols,rows,bits' — a cell is 1 when at least `cover` of its pixels have alpha >= alpha_min."""
    from PIL import Image
    a = Image.open(png).convert("RGBA").getchannel("A")
    w, h = a.size
    rows = max(1, round(cols * h / w))
    a = a.point(lambda v: 255 if v >= alpha_min else 0).resize((cols, rows), Image.BOX)
    bits = "".join("1" if v >= 255 * cover else "0" for v in a.tobytes())
    return f"{cols},{rows},{bits}"


def dump(m):
    """The manifest as JSON with one line per layer."""
    def one(o):
        return json.dumps(o, ensure_ascii=False)
    cvs = []
    for cv in m["canvases"]:
        head = {k: v for k, v in cv.items() if k != "layers"}
        rows = ",\n".join("     " + one(ly) for ly in cv["layers"])
        cvs.append("  " + one(head)[:-1] + ', "layers": [\n' + rows + "\n  ]}")
    return '{"canvases": [\n' + ",\n".join(cvs) + "\n]}\n"


def fill_masks(manifest_path):
    p = Path(manifest_path)
    base = p.parent
    m = json.loads(p.read_text(encoding="utf-8"))
    for cv in m["canvases"]:
        for ly in cv["layers"]:
            ly["mask"] = mask(base / ly["src"])
    p.write_text(dump(m), encoding="utf-8")
    print("ok", p, sum(len(cv["layers"]) for cv in m["canvases"]), "masks")


CSS_START, CSS_END = "      /* ── Layer playground (.ly-wrap)", "      .ly-hint b {"
JS_START, JS_END = "    <script>\n      /* Layer playground (.ly-wrap)", "      })();\n    </script>\n"


def sync(path):
    """Put the current LAYER_CSS / LAYER_JS into an HTML file: replace the blocks if present, otherwise add
    the CSS before the last </style> and the script before </body>."""
    p = Path(path)
    s = p.read_text(encoding="utf-8")
    if CSS_START in s:
        a = s.index(CSS_START)
        b = s.index("\n", s.index(CSS_END, a)) + 1
        s = s[:a].rstrip(" ").rstrip("\n") + "\n" + LAYER_CSS.lstrip("\n") + s[b:]
    else:
        i = s.rindex("    </style>")
        s = s[:i] + LAYER_CSS.lstrip("\n") + s[i:]
    if JS_START in s:
        a = s.index(JS_START)
        b = s.index(JS_END, a) + len(JS_END)
        s = s[:a] + LAYER_JS.lstrip("\n") + s[b:]
    else:
        i = s.rindex("  </body>")
        s = s[:i] + LAYER_JS.lstrip("\n") + s[i:]
    p.write_text(s, encoding="utf-8")
    print("ok", p)


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "masks":
        fill_masks(sys.argv[2])
    elif len(sys.argv) >= 3 and sys.argv[1] == "sync":
        sync(sys.argv[2])
    else:
        print(__doc__)
