"""Write templates/ai-tech-light/ from templates/byteplus/ + the byteplus-light look (slides-design skill).

Usage:
    python scripts/make_ai_tech_light.py            # template.html only
    python scripts/make_ai_tech_light.py --images   # also rebuild assets/img/bg-cover.jpg + bg-content.jpg

Same slides, CSS engine and media runtime as `byteplus`, same light look as `byteplus-light` (its LIGHT_CSS is
imported from make_byteplus_light.py), but brand-free: no logo in the chrome or on the cover, a generic
"About [Organisation]" timeline, [bracketed] product names. The cover / part / end background is the light
pptx-style circles with the AI icon (assets/img/ai-mark.png) in the middle circle.
Re-run after any change to templates/byteplus/template.html or make_byteplus_light.py.
Needs numpy + opencv-python only for --images.
"""
import re
import shutil
import sys
from pathlib import Path

from make_byteplus_light import LIGHT_CSS

SKILL = Path(__file__).resolve().parent.parent
SRC = SKILL / "templates" / "byteplus" / "template.html"
LIGHT_IMG = SKILL / "templates" / "byteplus-light" / "assets" / "img"
OUT_DIR = SKILL / "templates" / "ai-tech-light"
IMG = OUT_DIR / "assets" / "img"

AI_CSS = """
      /* ── AI TECH LIGHT: brand-free additions (generated by scripts/make_ai_tech_light.py) ── */
      .slide--about .tl { grid-template-columns: repeat(6, minmax(0, 1fr)); }
      .tl-logo.ph { font-size: calc(0.7 * var(--u)); background-color: #fff; }
"""

ABOUT = """      <!-- ═══════ SLIDE 2 · ABOUT [ORGANISATION] ═══════════════════════════════
           Organisation intro + 6-step milestone timeline. Every timeline item has an explicit grid-column/row —
           the .tl-hl highlight box (column 4) spans rows 2–5 and would shift auto-placed items.
           Replace each .tl-logo.ph with a .tl-logo div holding the milestone logo img. -->
      <section class="slide dark slide--about" id="s02">
        <div class="slide-chrome">
          <span class="label muted" data-anim="fade-in" data-delay="0">01 · [Organisation]</span>
        </div>

        <div class="slide-body">
          <div data-anim="fade-up" data-delay="1">
            <h2 class="h2" style="font-size: calc(2.4 * var(--u))">[Who We Are] <em>[What We Power]</em></h2>
            <p class="about-sub" style="margin-top: 0.8vh">[One-line positioning: what the organisation builds and for whom]</p>
          </div>
          <p class="about-text" data-anim="fade-up" data-delay="2">
            [Two to three sentences: where the organisation comes from, what its AI technology does for customers, and the outcome it delivers &mdash; faster decisions, lower cost, new growth.]
          </p>
          <div class="tl" data-anim="fade-up" data-delay="3">
{items}
          </div>
        </div>

        <div class="slide-foot">
          <span class="label muted">[Deck Title] · [Mon YYYY]</span>
          <span class="label muted">02 / 10</span>
        </div>
      </section>

"""


def about_slide():
    eras = [(1, 2, "[Era 1]"), (3, 2, "[Era 2]"), (5, 2, "[Era 3]")]
    rows = [f'            <div class="tl-era" style="grid-column: {c} / span {s}; grid-row: 1">{t}</div>' for c, s, t in eras]
    for c in range(1, 7):
        rows.append(f'            <div class="tl-logo ph" style="grid-column: {c}; grid-row: 2">Logo</div>')
    for c in range(1, 7):
        sub = "<span>[Detail]</span>" if c == 6 else ""
        rows.append(f'            <div class="tl-name" style="grid-column: {c}; grid-row: 3">[Milestone {c}]{sub}</div>')
    for c in range(1, 7):
        rows.append(f'            <div class="tl-dot" style="grid-column: {c}; grid-row: 4"><i></i></div>')
    for c in range(1, 7):
        rows.append(f'            <div class="tl-date" style="grid-column: {c}; grid-row: 5">[YYYY.M]</div>')
    rows.append('            <div class="tl-hl" style="grid-column: 4; grid-row: 2 / 6"></div>')
    return ABOUT.replace("{items}", "\n".join(rows))


def light_css():
    css = LIGHT_CSS
    css = css.replace("LIGHT THEME — BytePlus pptx master look (byteplus-light template)    ",
                      "LIGHT THEME — AI Tech Light (pale blue, brand-free)                  ")
    css = css.replace("scripts/make_byteplus_light.py; edit there, not here.   ",
                      "scripts/make_ai_tech_light.py; edit there, not here.    ")
    css = css.replace("bg-light-cover.jpg", "bg-cover.jpg").replace("bg-light-content.jpg", "bg-content.jpg")
    css = css.replace("the pptx layout images. Cover/part/end = circles + \"M\" icon",
                      "cover/part/end = circles + AI icon")
    css = css.replace('the cover background already carries the "M" icon', "the cover background carries the AI icon")
    css = css.replace("BytePlus blue", "blue")
    return css + AI_CSS


def build_html():
    s = SRC.read_text(encoding="utf-8")
    s = s.replace("<title>BytePlus Template</title>", "<title>AI Tech Light Template</title>", 1)
    # no layer-playground slide in this template (the CSS / script stay for decks that add one): drop slide 7, renumber
    a = s.index("      <!-- ═══════ SLIDE 7 · LAYER PLAYGROUND")
    b = s.index("      <!-- ═══════ SLIDE 8 ·")
    s = s[:a] + s[b:]
    for n in range(8, 12):
        s = s.replace(f'id="s{n:02d}"', f'id="s{n - 1:02d}"').replace(f"<!-- ═══════ SLIDE {n} ·", f"<!-- ═══════ SLIDE {n - 1} ·")
    s = re.sub(r"(\d\d) / 11<", lambda m: f"{int(m.group(1)) - (1 if int(m.group(1)) >= 8 else 0):02d} / 10<", s)
    # no logo anywhere, no part watermark (the background carries the AI icon)
    s, n_logo = re.subn(r'\n[ \t]*<img class="bp-logo[^>]*/>', "", s)
    s, n_mark = re.subn(r'\n[ \t]*<img class="part-mark"[^>]*/>', "", s)
    assert n_logo == 10 and n_mark == 1, (n_logo, n_mark)
    # generic About slide
    a = s.index("      <!-- ═══════ SLIDE 2 · ABOUT BYTEPLUS")
    b = s.index("      <!-- ═══════ SLIDE 3")
    s = s[:a] + about_slide() + s[b:]
    # brand words → placeholders
    s = s.replace("BytePlus Industry Solution", "[Organisation] · AI Solution")
    s = s.replace('<span class="tag">Seedream 5.0 Pro</span>', '<span class="tag">[Model A]</span>')
    s = s.replace('<span class="tag">Seedance 2.5</span>', '<span class="tag">[Model B]</span>')
    s = s.replace("<h3 class=\"h3\">Seedream 5.0</h3><p>Multimodal AI image generation and editing model</p>",
                  "<h3 class=\"h3\">[Model A]</h3><p>[What it does, in one line]</p>")
    s = s.replace("<h3 class=\"h3\">Seedance 2.5</h3><p>Advanced multimodal AI video generation model</p>",
                  "<h3 class=\"h3\">[Model B]</h3><p>[What it does, in one line]</p>")
    s = s.replace("1–2 product cards. bp-mark watermark.", "1–2 product cards.")
    # light look after the template's last style rules so it wins on equal specificity
    i = s.rindex("    </style>")
    s = s[:i] + light_css() + s[i:]
    left = re.findall(r"bytepl\w*|bytedance|seedream|seedance|byteplus_logo|bp-mark\.png", s, re.I)
    assert not left, sorted(set(left))
    (OUT_DIR / "template.html").write_text(s, encoding="utf-8")
    print("ok", OUT_DIR / "template.html", len(s), "bytes")


def build_images():
    """bg-content.jpg = the light gradient as is; bg-cover.jpg = the light circles with the centre mark
    painted out and ai-mark.png placed in the middle circle (soft white halo, light-to-deep blue fill)."""
    import cv2
    import numpy as np

    shutil.copy2(LIGHT_IMG / "bg-light-content.jpg", IMG / "bg-content.jpg")
    bg = cv2.imread(str(LIGHT_IMG / "bg-light-cover.jpg"))[..., ::-1].astype(np.float32)   # RGB
    h, w = bg.shape[:2]
    cx, cy = 1343, 563                                    # centre of the circles at 1920×1080
    Y, X = np.mgrid[0:h, 0:w]
    r = np.hypot(X - cx, Y - cy)
    known = (r >= 185).astype(np.float32)                 # paint out a disc around the old mark
    fill = cv2.GaussianBlur(bg * known[..., None], (0, 0), 60) / np.maximum(cv2.GaussianBlur(known, (0, 0), 60), 1e-4)[..., None]
    t = np.clip((r - 150) / 35, 0, 1)[..., None]
    out = bg * t + fill * (1 - t)

    mark = cv2.imread(str(IMG / "ai-mark.png"), cv2.IMREAD_UNCHANGED)
    alpha = mark[..., 3].astype(np.float32) / 255
    mh = 250
    mw = round(alpha.shape[1] * mh / alpha.shape[0])
    alpha = cv2.resize(alpha, (mw, mh), interpolation=cv2.INTER_AREA)
    canvas = np.zeros((h, w), np.float32)
    x0, y0 = cx - mw // 2, cy - mh // 2
    canvas[y0:y0 + mh, x0:x0 + mw] = alpha
    glow = cv2.GaussianBlur(canvas, (0, 0), 14)[..., None] * 0.7
    out = out * (1 - glow) + 255 * glow
    g = np.clip((Y - y0) / mh, 0, 1)[..., None]
    col = np.array([90, 165, 255], np.float32) * (1 - g) + np.array([0, 104, 255], np.float32) * g
    a = canvas[..., None] * 0.85
    out = out * (1 - a) + col * a
    cv2.imwrite(str(IMG / "bg-cover.jpg"), np.clip(out, 0, 255).astype(np.uint8)[..., ::-1], [cv2.IMWRITE_JPEG_QUALITY, 92])
    print("ok", IMG / "bg-cover.jpg", IMG / "bg-content.jpg")


if __name__ == "__main__":
    IMG.mkdir(parents=True, exist_ok=True)
    if "--images" in sys.argv:
        build_images()
    build_html()
