"""Write templates/byteplus-light/template.html from templates/byteplus/template.html (slides-design skill).

Usage:
    python scripts/make_byteplus_light.py

Same slides, CSS engine and media runtime as `byteplus`; only the look changes: the BytePlus pptx master's
light backgrounds (assets/img/bg-light-cover.jpg with the circles and "M" icon, bg-light-content.jpg gradient),
the dark-text wordmark (byteplus_logo_light.png), BytePlus blue #0068FF instead of gold, DM Sans titles and blue
gradient header bars. Re-run after any change to templates/byteplus/template.html so the two stay in sync; then re-run
make_ai_tech_light.py, which reuses LIGHT_CSS.
"""
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
SRC = SKILL / "templates" / "byteplus" / "template.html"
OUT = SKILL / "templates" / "byteplus-light" / "template.html"

LIGHT_CSS = """
      /* ╔══════════════════════════════════════════════════════════════════════╗
         ║  LIGHT THEME — BytePlus pptx master look (byteplus-light template)    ║
         ║  Generated by scripts/make_byteplus_light.py; edit there, not here.   ║
         ╚══════════════════════════════════════════════════════════════════════╝ */
      :root {
        --c-bg: #f5f8ff;
        --c-fg: #1d2028;
        --c-fg-2: #4e5969;
        --c-fg-3: #86909c;
        --c-accent: #0068ff;
        --c-border: #c6d6ef;
        --f-display: "DM Sans", "Noto Sans SC", system-ui, sans-serif;
        --f-heading: "DM Sans", "Noto Sans SC", system-ui, sans-serif;
        --tint-band: rgba(0, 104, 255, 0.09);
        --tint-box: rgba(0, 104, 255, 0.06);
        --card-bg: rgba(255, 255, 255, 0.8);
        --shadow-card: 0 1px 3px rgba(0, 60, 160, 0.06);
      }
      body { background: var(--c-bg); }

      /* Backgrounds: the pptx layout images. Cover/part/end = circles + "M" icon; content = soft gradient */
      .slide.dark {
        background: var(--c-bg) url("assets/img/bg-light-content.jpg") center / cover no-repeat;
        color: var(--c-fg);
      }
      .slide.dark.slide--cover,
      .slide.dark.slide--part,
      .slide.dark.slide--end { background-image: url("assets/img/bg-light-cover.jpg"); }
      .slide.dark::before { background-image: none; }
      .slide.dark > .part-mark { display: none; }   /* the cover background already carries the "M" icon */

      /* Type: bold sans titles, emphasis in BytePlus blue (no italics) */
      .display, .h1, .h2 { font-weight: 700; letter-spacing: -0.015em; }
      .slide h1 em, .slide h2 em, .h3 em, .lead em, .cover-sub em { font-style: normal; color: var(--c-accent); }
      .cover-title em { display: block; }   /* two lines: keeps the title clear of the background icon */

      /* Bands, boxes and highlights: blue tints instead of gold */
      .lede { background: var(--tint-band); border-left-color: var(--c-accent); color: var(--c-fg); }
      .tl-hl, .loc-prompt { background: var(--tint-box); }
      .cap-row.c3 .cap.on { background: var(--tint-band); }
      .edit-card { background: var(--card-bg); box-shadow: var(--shadow-card); }
      .part-card { background: var(--card-bg); box-shadow: var(--shadow-card); }

      /* Media: white surfaces, light overlays */
      .frame, .vid { background: #fff; }
      .frame.plate {
        background: #fff;
        border: 1px solid var(--c-border);
        box-shadow: 0 calc(0.4 * var(--u)) calc(1.6 * var(--u)) rgba(0, 60, 160, 0.10);
      }
      .vid .snd { background: rgba(255, 255, 255, 0.9); color: var(--c-fg); }
      .vid .play-btn svg { background: rgba(255, 255, 255, 0.88); fill: var(--c-accent); }
      .fb-content { background: linear-gradient(to bottom, transparent 0%, rgba(245, 248, 255, 0.92) 35%); }
      #lightbox { background: rgba(240, 245, 255, 0.95); }
      #lightbox img { box-shadow: 0 20px 60px rgba(0, 40, 120, 0.25); }
      #notes { background: rgba(255, 255, 255, 0.97); color: var(--c-fg); box-shadow: 0 10px 40px rgba(0, 40, 120, 0.18); }
      .ph {
        color: var(--c-fg-2);
        background: repeating-linear-gradient(135deg, rgba(0, 104, 255, 0.07) 0 12px, rgba(0, 104, 255, 0.02) 12px 24px);
      }

      /* Chrome: navigation readable on white */
      .nav-dot { background: rgba(29, 32, 40, 0.18); }
      .nav-dot.is-active { background: var(--c-accent); }
      #slide-counter { color: rgba(29, 32, 40, 0.35); }
"""


def main():
    s = SRC.read_text(encoding="utf-8")
    assert s.count("    </style>") >= 1 and "byteplus_logo_dark.png" in s
    s = s.replace("<title>BytePlus Template</title>", "<title>BytePlus Light Template</title>", 1)
    s = s.replace("assets/img/byteplus_logo_dark.png", "assets/img/byteplus_logo_light.png")
    # the light block goes after the template's last style rules so it wins on equal specificity
    i = s.rindex("    </style>")
    s = s[:i] + LIGHT_CSS + s[i:]
    OUT.write_text(s, encoding="utf-8")
    print("ok", OUT, len(s), "bytes")


if __name__ == "__main__":
    main()
